version: '3.8'

services:
    postgres:
      container_name: api-delliv
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: delliv
        PGDATA: /data/posgres
      volumes:
        - ./data/pg:/data/posgres