version: '3.8'

services:
    postgres:
      container_name: delliv-db
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: delliv
        PGDATA: /data/posgres
      volumes:
        - postgres_data:/data/posgres 

    node:
      container_name: delliv-api
      build: .
      command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start:dev"
      ports:
        - "3333:3333"
      environment:
        - NODE_ENV=dev
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        - postgres

    prisma-studio:
      container_name: prisma-studio
      build: .
      command: npx prisma studio --port 5555
      ports:
        - "5555:5555"
      volumes:
        - .:/usr/src/app
      depends_on:
        - postgres

volumes:
  postgres_data: 
    driver: local